### ISSUE TITLE
No handler for "no activity" state of a room

### ISSUE THREAD

**Issue by ledjajev** [brunoinds/socrative-extractor#2]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at renderizeData (model.js:18:15)
    at main (model.js:11:60)
    at model.js:6:5
```

**Comment by brunoinds** [comment]
Hi! Let me understaend better your issue: So, when an activity is not started yet and the user tries to extract the quiz, this error occurs. Right? 

If is that so, we can implement an check before displaying the data, if there is no activity, we throw and alert warning the user to wait for it.

**Comment by ledjajev** [comment]
Yeah! That’s what I’m talking about. May i do this by fork? I’d like to contribute to this project.

**Comment by brunoinds** [comment]
If you have a better correction, please, PR, we can merge it! Feel free to pull your code!

**Comment by ledjajev** [comment]
I wouldn’t claim that my skills are better than yours, but I definitely will PR.
